apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: argocd
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: {{.Values.clusterIssuer.name}}
spec:
  ingressClassName: {{.Values.ingress.name}}
  tls:
    - hosts:
        - argocd.{{.Values.ingress.domain}}
      secretName: {{.Values.ingress.argocd_tls_secret}}
  rules:
    - host: argocd.{{.Values.ingress.domain}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-server
                port:
                  number: {{.Values.service.argocd_port}}
