apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    email: {{ .Values.clusterIssuer.acmeEmail }}
    server: {{ .Values.clusterIssuer.acmeServer }}
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.name }}
