apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name }}-deployment
  labels:
    app: {{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.frontend.name }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: {{ .Values.frontend.image }}:{{ .Values.frontend.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.secrets.name_application }}
          env:
            - name: PORT
              value: "{{ .Values.frontend.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 15
            periodSeconds: 5
          resources:
            requests:          
              memory: {{ .Values.frontend.resources.requests.memory | quote }}
              cpu: {{ .Values.frontend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.frontend.resources.limits.memory | quote }}
              cpu: {{ .Values.frontend.resources.limits.cpu | quote }}
          imagePullPolicy: IfNotPresent
