apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer.name }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: {{ .Values.ingress.name }}
  tls:
    - hosts:
        - {{ .Values.ingress.domain }}
      secretName: {{ .Values.ingress.tls_secret }}
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.backend.name }}-service
                port:
                  number: {{ .Values.service.backend_port }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.name }}-service
                port:
                  number: {{ .Values.service.frontend_port }}
