apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}-deployment
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name }}
    spec:
      containers:
        - name: {{ .Values.redis.name }}
          image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name_application }}
                  key: REDIS_PASSWORD
          livenessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            exec:
              command: ["redis-cli", "-a", "$(REDIS_PASSWORD)", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:          
              memory: {{ .Values.redis.resources.requests.memory | quote }}
              cpu: {{ .Values.redis.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.redis.resources.limits.memory | quote }}
              cpu: {{ .Values.redis.resources.limits.cpu | quote }}
          imagePullPolicy: IfNotPresent
          command: [
            "redis-server",
            "--requirepass", "$(REDIS_PASSWORD)",
            "--appendonly", "yes",
            "--maxmemory", "256mb",
            "--maxmemory-policy", "allkeys-lru"
          ]

